module.exports = {
    in: "INSERT INTO mains (WORKTARGET,ACCESSOBJ,COMPANY,REPRESENTNAME,ACCESSNUM,CONFIRMNAME,CREATEDAT,UPDATEDAT) VALUES (:WORKTARGET,:ACCESSOBJ,:COMPANY,:REPRESENTNAME,:ACCESSNUM,:CONFIRMNAME,:CREATEDAT,:UPDATEDAT)",
    out: "UPDATE mains SET UPDATEDAT = :UPDATEDAT WHERE COMPANY = :COMPANY AND REPRESENTNAME = :REPRESENTNAME AND CREATEDAT = :CREATEDAT",
    log: "SELECT * FROM mains LEFT OUTER JOIN files ON mains.id = files.mainid WHERE mains.CREATEDAT BETWEEN ':START 00:00:00' AND ':END 23:59:59' ORDER BY mains.CREATEDAT DESC",
    sum: "INSERT INTO details (SUMMARY, MAINID) VALUES (:SUMMARY, :MAINID)",
    file: "INSERT INTO files VALUES (:FILENAME, :FILEPATH, :FILESIZE, :MAINID)",
}